### ISSUE TITLE
After update to  ersion:  v0.106.0-a.63+97361234 all static DHCP leases are gone.

### ISSUE THREAD

**Issue by keshabit** [AdguardTeam/AdGuardHome#2834]
After update to version:  v0.106.0-a.63+97361234 all static DHCP leases are gone. It was working without any problems.

My Adguard setup using RPI4 on raspbian. Pls help ASAP.

Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by keshabit** [comment]
Pre-requisites updated.

**Comment by ainar-g** [comment]
Thanks for the report, investigating.

**Comment by ainar-g** [comment]
There is a good chance that your static leases can still be recovered.  If you open the file `leases.db` and replace all instances where it says something like `"exp":-62135596800` (where `-62135596800` is any large negative number) with `"exp":1`.

The main issue, along with a couple of others, should be fixed on the edge channel as of snapshot 5243399d.  Apologies for the bug!

**Comment by keshabit** [comment]
This issue is not fixed yet! I upgraded to the patch Version: v0.106.0-a.67+5243399d and I added one static IP it worked but when I added all IPs of my segment it again displayed that no IP configured in static lease therefore many leases configuration issue persists. Also, pls let us know where is the IP definition fine it so difficult to input one by one static leases configuration.

**Comment by ainar-g** [comment]
> I upgraded to the patch Version: v0.106.0-a.67+5243399d and I added one static IP it worked but when I added all IPs of my segment it again displayed that no IP configured in static lease therefore many leases configuration issue persists.

That's odd, we cannot reproduce it.  Could you please provide answers to the following answers:

1.  Are the static IPs that you are setting within the range you entered and within the subnet mask?  See also #2838.
2.  Can you provide the [verbose logs] of AdGuard Home when you add the static leases?

We will keep testing in the meantime.

> Also, pls let us know where is the IP definition fine it so difficult to input one by one static leases configuration.

The `leases.db` file I mentioned earlier is a plain JSON file where the leases are stored, but the format is not stable and not designed to be edited manually.  We will consider adding an easier way to import several static leases in the following releases.

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by keshabit** [comment]
I am able to reproduce the scenario: is it expected, if we change the range of DHCP IP addresses (for dynamic allocation), DHCP Static leases field will go blank, even if it's not intersecting or mutually exclusive.

**Comment by keshabit** [comment]
Again, I added 12 IPs and I refreshed and "BOOM" all gone. No change in config while leases definition or dynamic allocation. I'm so tired of this. :(

**Comment by ainar-g** [comment]
We're sorry for the inconvenience.  The snapshot eb9526cc should fix #2838, as well as a couple of other DHCP bugs.  If that one still doesn't fix the issue for you, please provide all of the information that was requested before, because we really need it to diagnose the issue better.  That is:

1.  The IP range and the subnet mask you entered.
2.  If the static lease IP addresses are within the subnet.
3.  Verbose logs.
4.  The state of your `leases.db` and if you applied the manual fix provided above.

**Comment by keshabit** [comment]
My complains ends here, thank you @ainar-g appreciate your swift fixes!
