### ISSUE TITLE
Listening on IPv6 LLA is not possible

### ISSUE THREAD

**Issue by lars-1** [AdguardTeam/AdGuardHome#2926]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.0-b.1
* **How did you install AdGuard Home:**
  * snap
* **How did you setup DNS configuration:**
  * LXD
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04

I am trying to listen on an IPv6 LLA address, but AdGuard won't start if I add it to the configuration yaml.

### Expected Behavior
The configuration should accept IPv6 LLA adresses:
```yaml
bind_hosts:
  - 10.10.10.10
  - fe80::10%eth0
```

### Actual Behavior
For IPv6 LLA you need to specify an interface (e.g. eth0) but AdGuard does not start:
`Job for snap.adguard-home.adguard-home.service failed because the control process exited with error code.`

I tried escaping the percent sign but that resulted in `Couldn't parse config file: invalid IP address: fe80::10%%eth0`.

**Comment by lars-1** [comment]
Bug still exists in v0.106.3.

**Comment by jdeluyck** [comment]
Facing the same issue when trying to get Adguardhome to listen on an ULA, in my case fddf:xxx:xxx::x/64 -> same error. Probably same fix.

**Comment by EugeneOne1** [comment]
@lars-1, hello and sorry for the long response.  We've pushed the latest edge build that should now be able to serve DNS on link-local IPv6 addresses.  Could you please try it and tell if it works properly within your network?

**Comment by Chialya** [comment]
The use of IPv6 LLA addresses is wrong and should not be used! According to the specifications for IPv6, ULA addresses are used for this purpose!
Even if you define the network interface for LLA, end devices that can only reach the DNS via multiple hops can still not communicate to the DNS.
The use of ULA addresses works perfectly.

**Comment by EugeneOne1** [comment]
@lars-1, hello again.  We'll close the issue for now if you don't mind.  It works properly on our test machines, but feel free to reopen the issue if any problem occured with the implementation.
