### ISSUE TITLE
Let's Encrypt root cert expiration issues

### ISSUE THREAD

**Issue by bruvv** [AdguardTeam/AdGuardHome#3689]
**Short summary:** due to an Android bug Let's Encrypt certificates do not work for DNS-over-TLS anymore.

Your options:
* Specify the `--preferred-chain="ISRG Root X1"` argument for certbot.
* If you use lego, you can also specifiy `--preferred-chain`.
* You can use ZeroSSL instead of Let's Encrypt.
* [The helper script](https://github.com/ameshkov/legoagh) for lego was updated to support both ZeroSSL and `--preferred-chain`.

<details>
    <summary>Original issue text</summary>

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * https://github.com/Freekers/ansible-adguard
* **How did you setup DNS configuration:**
  * DNS over TLS on android 12
* **If it's a router or IoT, please write device model:**
  * Oracle cloud
* **CPU architecture:**
  * Oracle cloud
* **Operating system and version:**
  * Ubuntu

### Expected Behavior
As for about 1 year now adguard is running perfectly fine on my oracle cloud server. I have been using it stable on my android phones without issues.

### Actual Behavior
Out of the blue today it stopped working and Android is trowing the error: `unable to connect to Private DNS server`
When debugging more with linux I found out with this command: `kdig -d adguard.nielsvoorn.nl +tls-ca google.nl` that it is going to the wrong IP: `DEBUG: Querying for owner(adguard.nielsvoorn.nl.), class(1), type(1), server(172.21.64.1), port(853), protocol(TCP)`

### Additional Information
I have changed nothing not even updated the server and it stopped working out of the blue. I of course updated the server after the problem and also rebooted a few times but nothing helped. DNS of HTTPS is working fine. Can some please help debug this?
I checked the ports they are open. What I find weird is that when debugging the TLS server with kdig it is showing `server=172.21.64.1` but that isn't an IP that I know.
These are known by adguard:
```
127.0.0.1
::1
10.0.0.35
172.17.0.1
fd00::1
172.18.0.1
172.19.0.1
```

Verbose.log:
```
2021/09/30 18:37:08.683681 [info] Starting the DNS proxy server
2021/09/30 18:37:08.683717 [info] Cache TTL override is enabled. Min=10800, Max=259200
2021/09/30 18:37:08.683722 [info] Ratelimit is enabled and set to 25 rps
2021/09/30 18:37:08.683726 [info] The server is configured to refuse ANY requests
2021/09/30 18:37:08.683730 [info] DNS cache is enabled
2021/09/30 18:37:08.683737 [info] MaxGoroutines is set to 50
2021/09/30 18:37:08.683745 [info] Creating the UDP server socket
2021/09/30 18:37:08.683857 [info] Listening to udp://[::]:53
2021/09/30 18:37:08.683865 [info] Creating a TCP server socket
2021/09/30 18:37:08.683892 [info] Listening to tcp://[::]:53
2021/09/30 18:37:08.683896 [info] Creating a TLS server socket
2021/09/30 18:37:08.683913 [info] Listening to tls://[::]:853
2021/09/30 18:37:08.683919 [info] Creating a QUIC listener
2021/09/30 18:37:08.683976 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2021/09/30 18:37:08.684029 [info] Listening to quic://[::]:784
2021/09/30 18:37:08.779903 [info] Entering the UDP listener loop on [::]:53
2021/09/30 18:37:08.781399 [info] Entering the tcp listener loop on [::]:53
2021/09/30 18:37:08.781433 [info] Entering the tls listener loop on [::]:853
2021/09/30 18:37:08.781456 [info] Entering the DNS-over-QUIC listener loop on [::]:784
2021/09/30 18:42:56.401974 [info] Start reconfiguring the server
2021/09/30 18:42:56.406416 [info] Stopping the DNS proxy server
2021/09/30 18:42:56.406495 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/09/30 18:42:56.406551 [info] Stopped the DNS proxy server
2021/09/30 18:42:56.512552 [info] Starting the DNS proxy server
2021/09/30 18:42:56.512582 [info] Cache TTL override is enabled. Min=10800, Max=259200
2021/09/30 18:42:56.512586 [info] The server is configured to refuse ANY requests
2021/09/30 18:42:56.512591 [info] DNS cache is enabled
2021/09/30 18:42:56.512596 [info] MaxGoroutines is set to 50
2021/09/30 18:42:56.512603 [info] Creating the UDP server socket
2021/09/30 18:42:56.512668 [info] Listening to udp://[::]:53
2021/09/30 18:42:56.512676 [info] Creating a TCP server socket
2021/09/30 18:42:56.512700 [info] Listening to tcp://[::]:53
2021/09/30 18:42:56.512705 [info] Creating a TLS server socket
2021/09/30 18:42:56.512722 [info] Listening to tls://[::]:853
2021/09/30 18:42:56.512727 [info] Creating a QUIC listener
2021/09/30 18:42:56.512810 [info] Listening to quic://[::]:784
2021/09/30 18:42:56.512988 [info] Entering the UDP listener loop on [::]:53
2021/09/30 18:42:56.513031 [info] Entering the tcp listener loop on [::]:53
2021/09/30 18:42:56.513051 [info] Entering the tls listener loop on [::]:853
2021/09/30 18:42:56.513066 [info] Entering the DNS-over-QUIC listener loop on [::]:784
2021/09/30 18:43:30.181146 [info] number of certs - 3
2021/09/30 18:43:30.181172 [info] got an intermediate cert
2021/09/30 18:43:30.181184 [info] got an intermediate cert
2021/09/30 18:43:30.512066 [info] number of certs - 3
2021/09/30 18:43:30.512088 [info] got an intermediate cert
2021/09/30 18:43:30.512095 [info] got an intermediate cert
2021/09/30 18:43:33.605991 [info] number of certs - 3
2021/09/30 18:43:33.606014 [info] got an intermediate cert
2021/09/30 18:43:33.606021 [info] got an intermediate cert
2021/09/30 18:43:38.658427 [info] number of certs - 3
2021/09/30 18:43:38.658452 [info] got an intermediate cert
2021/09/30 18:43:38.658459 [info] got an intermediate cert
2021/09/30 18:43:38.659817 [info] tls config settings have changed, will restart HTTPS server
2021/09/30 18:43:38.665830 [info] Start reconfiguring the server
2021/09/30 18:43:38.665842 [info] Stopping the DNS proxy server
2021/09/30 18:43:38.665916 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/09/30 18:43:38.665961 [info] Stopped the DNS proxy server
2021/09/30 18:43:38.767061 [info] Starting the DNS proxy server
2021/09/30 18:43:38.767085 [info] Cache TTL override is enabled. Min=10800, Max=259200
2021/09/30 18:43:38.767090 [info] The server is configured to refuse ANY requests
2021/09/30 18:43:38.767095 [info] DNS cache is enabled
2021/09/30 18:43:38.767099 [info] MaxGoroutines is set to 50
2021/09/30 18:43:38.767119 [info] Creating the UDP server socket
2021/09/30 18:43:38.767169 [info] Listening to udp://[::]:53
2021/09/30 18:43:38.767175 [info] Creating a TCP server socket
2021/09/30 18:43:38.767201 [info] Listening to tcp://[::]:53
2021/09/30 18:43:38.767241 [info] Entering the UDP listener loop on [::]:53
2021/09/30 18:43:38.767299 [info] Entering the tcp listener loop on [::]:53
2021/09/30 18:43:45.935703 [info] number of certs - 3
2021/09/30 18:43:45.935723 [info] got an intermediate cert
2021/09/30 18:43:45.935764 [info] got an intermediate cert
2021/09/30 18:43:48.707218 [info] number of certs - 3
2021/09/30 18:43:48.707243 [info] got an intermediate cert
2021/09/30 18:43:48.707249 [info] got an intermediate cert
2021/09/30 18:43:52.321101 [info] number of certs - 3
2021/09/30 18:43:52.321127 [info] got an intermediate cert
2021/09/30 18:43:52.321133 [info] got an intermediate cert
2021/09/30 18:43:52.322349 [info] tls config settings have changed, will restart HTTPS server
2021/09/30 18:43:52.327748 [info] Start reconfiguring the server
2021/09/30 18:43:52.327759 [info] Stopping the DNS proxy server
2021/09/30 18:43:52.327819 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/09/30 18:43:52.327829 [info] Stopped the DNS proxy server
2021/09/30 18:43:52.429214 [info] Starting the DNS proxy server
2021/09/30 18:43:52.429238 [info] Cache TTL override is enabled. Min=10800, Max=259200
2021/09/30 18:43:52.429242 [info] The server is configured to refuse ANY requests
2021/09/30 18:43:52.429246 [info] DNS cache is enabled
2021/09/30 18:43:52.429252 [info] MaxGoroutines is set to 50
2021/09/30 18:43:52.429258 [info] Creating the UDP server socket
2021/09/30 18:43:52.429303 [info] Listening to udp://[::]:53
2021/09/30 18:43:52.429310 [info] Creating a TCP server socket
2021/09/30 18:43:52.429335 [info] Listening to tcp://[::]:53
2021/09/30 18:43:52.429355 [info] Creating a TLS server socket
2021/09/30 18:43:52.429373 [info] Listening to tls://[::]:853
2021/09/30 18:43:52.429378 [info] Creating a QUIC listener
2021/09/30 18:43:52.429446 [info] Listening to quic://[::]:784
2021/09/30 18:43:52.429516 [info] Entering the UDP listener loop on [::]:53
2021/09/30 18:43:52.429567 [info] Entering the tls listener loop on [::]:853
2021/09/30 18:43:52.429586 [info] Entering the DNS-over-QUIC listener loop on [::]:784
2021/09/30 18:43:52.429592 [info] Entering the tcp listener loop on [::]:53
2021/09/30 18:43:52.429969 [info] Go to https://adguard.nielsvoorn.nl
2021/09/30 18:44:53.639183 [info] number of certs - 3
2021/09/30 18:44:53.639211 [info] got an intermediate cert
2021/09/30 18:44:53.639217 [info] got an intermediate cert
2021/09/30 18:44:53.968158 [info] number of certs - 3
2021/09/30 18:44:53.968181 [info] got an intermediate cert
2021/09/30 18:44:53.968189 [info] got an intermediate cert
2021/09/30 18:45:12.687750 [info] Start reconfiguring the server
2021/09/30 18:45:12.687765 [info] Stopping the DNS proxy server
2021/09/30 18:45:12.687818 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/09/30 18:45:12.687857 [info] Stopped the DNS proxy server
2021/09/30 18:45:12.789548 [info] Starting the DNS proxy server
2021/09/30 18:45:12.789581 [info] Cache TTL override is enabled. Min=10800, Max=259200
2021/09/30 18:45:12.789586 [info] The server is configured to refuse ANY requests
2021/09/30 18:45:12.789590 [info] DNS cache is enabled
2021/09/30 18:45:12.789596 [info] MaxGoroutines is set to 50
2021/09/30 18:45:12.789601 [info] Fastest IP is enabled
2021/09/30 18:45:12.789607 [info] Creating the UDP server socket
2021/09/30 18:45:12.789667 [info] Listening to udp://[::]:53
2021/09/30 18:45:12.789674 [info] Creating a TCP server socket
2021/09/30 18:45:12.789723 [info] Listening to tcp://[::]:53
2021/09/30 18:45:12.789730 [info] Creating a TLS server socket
2021/09/30 18:45:12.789748 [info] Listening to tls://[::]:853
2021/09/30 18:45:12.789754 [info] Creating a QUIC listener
2021/09/30 18:45:12.789850 [info] Listening to quic://[::]:784
2021/09/30 18:45:12.789983 [info] Entering the tcp listener loop on [::]:53
2021/09/30 18:45:12.790014 [info] Entering the UDP listener loop on [::]:53
2021/09/30 18:45:12.790044 [info] Entering the tls listener loop on [::]:853
2021/09/30 18:45:12.790057 [info] Entering the DNS-over-QUIC listener loop on [::]:784
```
</details>

**Comment by ainar-g** [comment]
Hello.  Do you happen to use Let's Encrypt certs by any chance?  Their root cert [expired today][1].

[1]: https://www.appviewx.com/blogs/lets-encrypt-root-certificate-expiration-should-you-worry/

**Comment by AbhyudayaSharma** [comment]
Same for me. DoT stopped working all of a sudden today. I'm running Ubuntu 20.04 on a Digital Ocean droplet.

If I enable verbose logging, I get this:

```
2021/09/30 17:12:22.634683 3751#588 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): Start handling the new tls connection xxx.xxx.xxx.xxx:41806
2021/09/30 17:12:22.640535 3751#587 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): Start handling the new tls connection xxx.xxx.xxx.xxx:47492
2021/09/30 17:12:38.936959 3751#589 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): Start handling the new tls connection xxx.xxx.xxx.xxx:47502
```

**Comment by AbhyudayaSharma** [comment]
> Hello. Do you happen to use Let's Encrypt certs by any chance? Their root cert [expired today](https://www.appviewx.com/blogs/lets-encrypt-root-certificate-expiration-should-you-worry/).

@ainar-g Yes, I'm using letsencrypt. My certificate will expire in November.

**Comment by BA7JCM** [comment]
我也有相同的问题，我分别搭建在我租的服务器上和自己家里的电脑上的也是突然dot无法工作，但是doh正常，服务器上是centos8，家里的电脑上是Debian11

**Comment by bruvv** [comment]
Yup I'm using let's encrypt @ainar-g and with Linux server swag container my certification is valid till November.

**Comment by ameshkov** [comment]
It does not matter when your cert expires, what matters is that their root is expired. If you don't have their new root on the device, it won't trust your cert anymore.

**Comment by AbhyudayaSharma** [comment]
Well, my certificate is signed by ISRG R3. ISRG R3 cert is signed by ISRG Root X1. All my devices do have the X1 certificate in their trust stores.

**Comment by bruvv** [comment]
Than how will we get a new certificate ? (Using swag container)

**Comment by mJones00** [comment]
I had the same issue just this afternoon. The web portal on port 443 works fine and DoH is also working fine except for DoT. is it something related to certificate, why is it still working for DoH and the portal ? they also share the same certs in my setup.

**Comment by ameshkov** [comment]
Tbh, I've no idea what's wrong with LE.

Using [dnslookup](https://github.com/ameshkov/dnslookup) from my laptop it seems that DoT is okay. But it does not work when I try it from an Android device:
```
09-30 20:39:11.163  1017  8479 W resolv  : SSL_connect ssl error =1, mark 0xf0071: No such file or directory
09-30 20:39:11.163  1017  8479 W resolv  : TLS Handshake failed
09-30 20:39:11.163  1017  8479 W resolv  : query failed
09-30 20:39:11.163  1017  8479 W resolv  : validateDnsTlsServer returned 0 for x.x.x.x
09-30 20:39:11.163  1017  8479 W resolv  : Validation failed
```

**Comment by tancysam** [comment]
Referencing this [page](https://community.letsencrypt.org/t/android-devices-with-dot-configured-interaction-with-new-default-chain/161020/19) 

`certbot -q renew --preferred-chain="ISRG Root X1"`
This should solve the problem.

**Comment by ameshkov** [comment]
Alternative solution would be to use ZeroSSL, seems to be working okay with Android.

**Comment by mJones00** [comment]
will the option --preferred-chain="ISRG Root X1" affect the web portal or other services that uses the same certs ?

**Comment by bnkas** [comment]
I cannot get LE to work no matter what I tried. Either it is an Android problem or LE problem.. not worth more effort. 

ZeroSSL solves the problem and Acme.sh started using it as default CA a while ago.

**Comment by fightforlife** [comment]
Same error here using LineageOS18.1 (Android11), starting today.
Using pomerium autocert (letsencrypt). I did not find an easy way to change the cain yet.

As far as I understand this means the android device needs to be updated?

**Comment by ameshkov** [comment]
> As far as I understand this means the android device needs to be updated?

Not really. You need to either use ZeroSSL or generate a new LE cert using `--preferred-chain="ISRG Root X1"`.

**Comment by fightforlife** [comment]
Ok thank you, I will try to use ZeroSSL in the future.
I just pulled a new LE cert and the same error is still present. The root is already ISRG Root X1 and valid, as far as I understand.
![image](https://user-images.githubusercontent.com/5511687/135522026-178bfe9b-0551-4082-be09-d08639034a2d.png)

**Comment by ameshkov** [comment]
@fightforlife make sure that you're using the latest versions of certbot/lego.

I've updated the doc and added information about this preferred chain argument:  https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#certbot-dnschallenge

Keeping this issue open until tomorrow.

**Comment by r1bnc** [comment]
For those who can't renew yet you can try to remove the last certificate from fullchain.pem, and it should fix the problem. As per https://community.letsencrypt.org/t/android-devices-with-dot-configured-interaction-with-new-default-chain/161020/19

**Comment by webmihir** [comment]
> @fightforlife make sure that you're using the latest versions of certbot/lego.
> 
> I've updated the doc and added information about this preferred chain argument: https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#certbot-dnschallenge
> 
> Keeping this issue open until tomorrow.

Thanks. Using the new flag for preferred chain (and --force-renew worked since I was >30days away from my certificate expiration) worked for me. Private DNS on Android (DoT) works again.

**Comment by guidocioni** [comment]
Even after following all the suggestions I cannot fix this issue. DoT works for me but DoH does not 

```
$ dnslookup www.google.de https://dnsserver
dnslookup 1.4.9
2021/10/01 09:15:11 Cannot make the DNS request: couldn't unpack DNS response from 'https://dnsserver:443': body is <!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><meta name="google" content="notranslate"><link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon-180x180.png"/><meta name="mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="mask-icon" href="assets/safari-pinned-tab.svg" color="#67B279"><link rel="icon" type="image/png" href="assets/favicon.png" sizes="48x48"><title>Login</title><link href="login.613b75eb03ab9fa3e21b.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="login.613b75eb03ab9fa3e21b.js"></script></body></html>, cause: dns: bad rdata

$ dnslookup www.google.de tls://dnsserver
dnslookup 1.4.9
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 41889
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.de.	IN	 A

;; ANSWER SECTION:
www.google.de.	293	IN	A	142.250.185.195

```

I can still use internet at home cause my router supports DoT but on my android phone (Pixel 5) I can only specify the address and not the protocol, so it fails because it probably tries DoH at first. 

What I did was
 - installing the latest version of certbot using snap (version coming with Ubuntu is too old)
 - force a renew of the certificates `sudo certbot --force-renewal --preferred-chain="ISRG Root X1" renew`
 - pointing adsguard to the new certificates 

Of course the web interface is working fine and the certificates chain in Chrome shows as valid 

<img width="191" alt="Screenshot 2021-10-01 at 09 22 08" src="https://user-images.githubusercontent.com/12760310/135581383-f25cda35-8b1b-4a06-88a8-85bf5dff6c93.png">

Can anyone tell me what I'm doing wrong? :)

**Comment by ameshkov** [comment]
> Can anyone tell me what I'm doing wrong? :)

Could it be that you forgot to specify the full path for DOH?

Should be something like that:
`dnslookup www.google.de https://dnsserver/dns-query`

**Comment by ameshkov** [comment]
Closing this issue.

I've updated the issue description and explained possible solutions there.

**Comment by guidocioni** [comment]
> > Can anyone tell me what I'm doing wrong? :)
> 
> Could it be that you forgot to specify the full path for DOH?
> 
> Should be something like that: `dnslookup www.google.de https://dnsserver/dns-query`

You're right, I forgot that when over HTTPS you have to use the subfolder `/dns-query`. By the way I solved the problem on Android by restarting the phone (:D)

**Comment by fightforlife** [comment]
For me DNS lookup works correct and my PC is able to use DoT correctly.
But my phone (lineage os 18.1) and my router (Fritzbox) are not able to connect. I will try to get to the bottom of this.

**Comment by guidocioni** [comment]
> For me DNS lookup works correct and my PC is able to use DoT correctly. But my phone (lineage os 18.1) and my router (Fritzbox) are not able to connect. I will try to get to the bottom of this.

I have a fritz box as well. it should use DoT so if that's protocol is working you should be fine. Did you by any chance reboot the router? i know it's stupid but I've noticed it multiple times 😁

**Comment by fightforlife** [comment]
my issue is coming from pomerium, which is using envoy whic is using boringssl (for anyone also using pomerium as a reverse proxy)
https://github.com/pomerium/pomerium/issues/2653
https://bugs.chromium.org/p/boringssl/issues/detail?id=439#c4

**Comment by fightforlife** [comment]
I tried it with two phones, which should be quite up to date:
Xiaomi Poco F1 with  lineage-18.1-20211009-nightly-beryllium-signed.zip
Google Pixel4a with latest Android 11 update.

I am using pomerium as a reverse proxy, which also creates the used certificate automatically.
They just introduced a new commit which removes the old letsencrypt CA. I will try and give some feedback.
