### ISSUE TITLE
DNS rewrites not responding with appropriate address in web browsers

### ISSUE THREAD

**Issue by MannyJ1** [AdguardTeam/AdGuardHome#4004]
### Issue Details

* **Version of AdGuard Home server:**
 Version: v0.107.0
  
* **How did you install AdGuard Home:**
Installed via Home Assistant integrations
 
* **How did you setup DNS configuration:**
Adguard Home DNS configured for use on  (Windows 10) device

* **If it's a router or IoT, please write device model:**
 Raspberry Pi 3 Model B+

* **CPU architecture:**
Cortex-A53 64-bit

* **Operating system and version:**
HomeAssistantOS6.2 (https://www.home-assistant.io/blog/2021/06/11/home-assistant-os-release-6/)

### Expected Behavior
DNS Rewrites are meant to redirect the user to the inputted address, instead of the original address. For example google.com can be rewritten to facebook.com with the appropriate rewritten response. 

### Actual Behavior
The DNS rewrite log is correctly displayed, however, the actual rewriting only occurs when using tools such as nslookup, but does not occur in any web browser.

### Screenshots

<details><summary>Screenshot: Log</summary>

![Screenshot 2021-12-24 234729](https://user-images.githubusercontent.com/37697173/147354319-3b0a2a0a-7f53-4912-9d23-58830a4c3d15.png)

</details>

<details><summary>Screenshot: Nslookup</summary>

![Screenshot 2021-12-24 234753](https://user-images.githubusercontent.com/37697173/147354363-7e156ce9-1844-43ff-93e7-cb7a0548a378.png)

</details>

<details><summary>Screenshot: DNS rewrite entry</summary>

![Screenshot 2021-12-24 235844](https://user-images.githubusercontent.com/37697173/147354429-6931c788-9b6b-49a5-a3b9-088aff1be265.png)

</details>

**Comment by ainar-g** [comment]
Hello and thank you for the report!  A few questions to help us reproduce the issue:

1.  What browser are you using?  Google Chrome and similar browsers, including Microsoft Edge, are known to [ignore the system-wide DNS server][1].

2.  Does this also occur with the newer [`$dnsrewrite`][1] rules?  Like:

    ```none
    ||youtube.com^$dnsrewrite=facebook.com
    ```

    (Put this into the input on the “Filtering → Custom Filtering Rules” page.)

[1]: https://networkguy.de/google-chrome-ignores-the-local-dns-server/

**Comment by MannyJ1** [comment]
Thanks for the prompt response @ainar-g! I've followed the hyperlink you mentioned and have turned off secure DNS in Chrome settings. This seemed to have changed the original behaviour I described. After this change, websites do not load all their assets, however they do not redirect either (even though the log shows that its been rewritten). For example, I used the custom DNS rewrite rule you mentioned with iCloud.com: 

<details><summary>Screenshot: Query log</summary>

![Screenshot 2021-12-25 010008](https://user-images.githubusercontent.com/37697173/147357858-4dd56170-c77f-4714-9eb8-9caebae3c65c.png)

</details>

<details><summary>Screenshot: iCloud page (not all assets loaded)</summary>

![Screenshot 2021-12-25 010019](https://user-images.githubusercontent.com/37697173/147357884-f8934602-fa0d-448a-98e4-519479e5bd73.png)

</details>

**Comment by ainar-g** [comment]
@MannyJ1, we've pushed a new version to the `edge` channel that restores some of the behaviour of rewrites to the one from v0.106.3.  Could you please check if that version improves DNS rewrites for you?

**Comment by ZeroClover** [comment]
What you are trying to achieve is [URL redirection](https://en.wikipedia.org/wiki/URL_redirection), which is not something that a DNS server can do.

**Comment by agneevX** [comment]
> What you are trying to achieve is URL redirection, which is not something that a DNS server can do.

There should be a primer somewhere for what DNS can and can't do, since this seems to come up pretty frequently.

**Comment by zybster** [comment]
I'm having the same issue and also the edge version does not fix it.
I'm running Adguard via Docker with the official docker hub image.

This is not a browser related problem.
I tested with DIG against the adguard host and the reply simply ignored all DNS rewrites.
This is really a problem since I'm running a lot of home internal services which should be resolved with their internal IPs instead of my external one.
A downgrade to 0.106.3 did not work either because of "schema" changes ?!

Would be great if this feature could be fixed as soon as possible

**Comment by agneevX** [comment]
@zybster can your provide details about what is it you're trying to do and what you've done so far?
