### ISSUE TITLE
DNS rewrite after update v0107 not working well

### ISSUE THREAD

**Issue by KGBist2000** [AdguardTeam/AdGuardHome#4008]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * V0.107.0
* **How did you install AdGuard Home:**
  * source
* **How did you setup DNS configuration:**
  * Client -> Adguard (Proxmox, 192.168.76.3)-> Unbound (same machine as Adguard 127.0.0.1:5335) -> dns-root-server 
* **If it's a router or IoT, please write device model:**
  * Proxmox lxc 
* **CPU architecture:**
  * Intel x86
* **Operating system and version:**
  * ubuntu 20.04 LTS

### Expected Behavior

DNS rewrite is working as it was before update V0.106.3 -> V0.107.0

### Actual Behavior

before the update it was enough to define:
- sub.domain.com -> 192.168.0.1 and all queries A,AAAA,HTTPS was well rewritten

After update to V0.107.0 dns rewrite ist no working:
- sub.domain.com -> 192.168.0.1 

Issues:
- V0.107.0 need for each query an own ENTRY e.g. additional AAAA record
- V0.107.0 is no able to manage HTTPS-Queries and do not rewrite, it is forwarding it to the next DNS-Server

Additionally some apps are requesting HTTPS-Queries. All HTTPS queries are sended to public DNS and are not rewritten by Adguard . see screenshots.

With this configuration Adguard V0.107.0 is not useable at home-network.

I have to go back to V0.106.3 to make my network workable.

### Screenshots
![image](https://user-images.githubusercontent.com/81825812/147357210-b4d6b963-e149-4231-bdd0-6f617f25371f.png)
![image](https://user-images.githubusercontent.com/81825812/147357435-815d1667-e303-42bb-a229-476dec35a50c.png)
![image](https://user-images.githubusercontent.com/81825812/147357592-33ff77f6-7585-491e-8b27-0d0157073fb5.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hello and thank you for the thorough report!  It seems that the behaviour there has indeed changed between the two releases.  We'll fix it by v0.107.1.

**Comment by ainar-g** [comment]
@KGBist2000, we've pushed a new version to the `edge` channel that restores the rewrite behaviour from v0.106.3.  Could you please check if that version fixes the issue for you?

**Comment by antoinelibert** [comment]
Hello, I had the same exact problem. Fixed by using the latest `edge` version. Thanks!

**Comment by ainar-g** [comment]
We'll close this issue for now.  Please feel free to reopen if there are still bugs.

**Comment by mikedodge04** [comment]
Im on Version: v0.107.8 and DNS Rewrites are still an issue. I am seeing the same behavior as reported.

**Comment by ainar-g** [comment]
@mikedodge04, apologies for the long wait.  If the issue is still there in the latest versions, and `$dnsrewrite` rules don't fix it, please file a new issue with all the details.  Thanks.
