### ISSUE TITLE
Sysvinit service does not start AdGuardHome on boot

### ISSUE THREAD

**Issue by nandlab** [AdguardTeam/AdGuardHome#4480]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.5
* **How did you install AdGuard Home:**
  * `curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v`
* **How did you setup DNS configuration:**
  * No change.
* **If it's a router or IoT, please write device model:**
  * It is a ThinkPad.
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Devuan GNU/Linux 4 (chimaera) x86_64

### Expected Behavior
AdGuard Home should start automatically on boot.

### Actual Behavior
AGH installed normally and placed the service `/etc/init.d/AdGuardHome` and created symlinks in `/etc/rc?.d/`.

But it is not started on boot. `sudo service --status-all` prints `[ - ]  AdGuardHome`, which means it is not running.

Although I can start it manually with `sudo service AdGuardHome start`.

**Comment by jumpsmm7** [comment]
> 

@nandlab 
Have you tried to enable it with commands like

**sudo systemctl enable AdGuardHome**
** sudo systemctl daemon-reload**

**Comment by nandlab** [comment]
@jumpsmm7
Thanks for the reply!

I do not have systemd, so `sudo systemctl enable AdGuardHome.service` returns `sudo: systemctl: command not found`.

**Comment by jumpsmm7** [comment]
> @jumpsmm7 Thanks for the reply!
> 
> I do not have systemd, so `sudo systemctl enable AdGuardHome.service` returns `sudo: systemctl: command not found`.

Okay

**Comment by EugeneOne1** [comment]
@nandlab, the issue should be fixed as per the last edge build.  Could you please check if it now starts on boot?

Note, that you may install the edge build via the script using [these](https://github.com/AdguardTeam/AdGuardHome/#test-unstable-versions) commands.  Consider also backing up your `data` directory and the configuration file.

**Comment by ainar-g** [comment]
We'll close this issue for now.  Please feel free to open new ones if you find anything.

**Comment by nandlab** [comment]
Hello,
sorry, I did not have time to test it before.

I installed the edge build and the init script itself seems to work. I can manually start AdGuardHome and check its status.
- `sudo invoke-rc.d AdGuardHome start`
- `sudo invoke-rc.d AdGuardHome status` prints `Running`

But it is still does not start at boot.

It looks like the init scripts are installed incorrectly in `/etc/rc?.d/`.
For example the following symlink is created: `/etc/rc2.d/S50AdGuardHome -> /etc/init.d/AdGuardHome`.
Other symlinks look like this: `/etc/rc2.d/S01console-setup.sh -> ../init.d/console-setup.sh`.

Maybe the following things can cause problems:
1. `S50AdGuardHome` references the absolute path `/etc/init.d/AdGuardHome` instead of the relative `../init.d/AdGuardHome`.
2. Its sequence number 50 is very large and it comes after `/etc/rc2.d/S07rc.local -> ../init.d/rc.local` which is normally the last script to be executed in a runlevel.

I can fix it by running `sudo update-rc.d AdGuardHome defaults`, which renames the symlink to `S02AdGuardHome`. Then AdGuardHome starts on boot.

Maybe you can install the init script correctly by running something like `sudo update-rc.d AdGuardHome defaults` in the installation script.

**Comment by nandlab** [comment]
Can you please reopen this issue?
