### ISSUE TITLE
Possibility for wildcards in "ignored domains"

### ISSUE THREAD

**Issue by RealKev79** [AdguardTeam/AdGuardHome#5720]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Within the "ignored domains" in logs-configuration and statistics-configuration I want to add several domains with wildcards because I do not want to "see" every single subdomain or similar from a specific domain. For example I want to add following domain:
*.blabla.org
and this should trigger on "www.blabla.org" and also on "blablablabla.blabla.org"

I have a working laptop and when I am working at home I did not want to see the whole specific company domains.

At the moment I added these into the "disallowed domains" in the DNS-Settings. 

Regards
Kevin

**Comment by davralin** [comment]
In the same situation myself, I don't want to see my monitoring setup's continous query of my internal hosts - so I want to exclude my entire local DNS-name from the query log.

@RealKev79 
How does it work with having those DNS-records in `Disallowed domains` ? The way I understand the help-text, those domains wont be resolved at all?

**Comment by RealKev79** [comment]
@davralin 
Yes the domains entered in "disallowed domains" are completly ignored and are not resolved. Because of that "issue" it will be an effort if the domains can entered in the  "ignored domains" within the "general settings" / "logs configuration" as I mentioned above.

**Comment by ainar-g** [comment]
AdBlock syntax is going to be supported in v0.107.37.

**Comment by whyisthisbroken** [comment]
So i can now put *in-addr.arpa in the Ignored Field ?
because I still see the entries.
Will there possibly be a UI added? Maybe in the same button where you can also block?

**Comment by FFFcat** [comment]
> So i can now put *in-addr.arpa in the Ignored Field ? because I still see the entries. Will there possibly be a UI added? Maybe in the same button where you can also block?

AdBlock syntax such as `||in-addr.arpa`, it's just hidden

**Comment by jeverley** [comment]
Is it expected that we should be able to use the AdBlock $client syntax in the rules?

||168.192.in-addr.arpa
||example.com^$client=192.168.1.6

With the above I successfully exclude the arpa queries, but I can still see entries for _example.com_ from the specified client IP.

**Comment by gpz1100** [comment]
> Is it expected that we should be able to use the AdBlock $client syntax in the rules?
> 
> ||168.192.in-addr.arpa ||example.com^$client=192.168.1.6
> 
> With the above I successfully exclude the arpa queries, but I can still see entries for _example.com_ from the specified client IP.

Have you been able to find a solution to this?  I'm trying to do the exact same thing.  I have one client (a thermostat) the wants to reach out and touch amazon, every 50 seconds). I can block this by dns or at firewall level (by blocking the entire amazon asn for that client). With dns block, I see a block entry every 50 seconds.  I would love to not see that, but still see such entries from other clients.
