### ISSUE TITLE
Error: control/filtering/add_url 

### ISSUE THREAD

**Issue by tomasenskede** [AdguardTeam/AdGuardHome#5851]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version
v0.107.29
Docker/Proxmox

#### What did you do?
add DNS filter
#### Expected result
filter added
#### Actual result
POST <host>:83 /control/filtering/add_url: Couldn't fetch filter from url https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt: Get "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt": resolving "adguardteam.github.io": requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=AAABAAABAAAAAAABC2FkZ3VhcmR0ZWFtBmdpdGh1YgJpbwAAAQABAAApCAAAAIAAAAA": all dialers failed: 2 errors: "dial tcp [2620:fe::10]:443: connect: cannot assign requested address", "dial tcp [2620:fe::fe:10]:443: connect: cannot assign requested address"
#### Screenshots (if applicable)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/32595351/d3071fc7-52ae-4afc-bf5d-256d1c76da5e)

**Comment by Khaled0Ebrahim** [comment]
Seems like your AGH can't resolve the url for some reason. 1- please provide a screenshot for your dns settings
2- is the dns server working at the moment? like if you used AGH you can reach sites?

**Comment by tomasenskede** [comment]
After encountering some issues with AdGuard, I decided to take a troubleshooting approach. The first step I took was to uninstall the application completely from my device. Once the uninstallation process was completed, I proceeded to reinstall AdGuard.

To my relief, the reinstallation resolved the problem, and AdGuard started functioning properly again. However, despite my efforts, I was unable to determine the exact cause of the initial error. It remains a mystery why the application stopped working in the first place.

Nevertheless, I am pleased that the issue has been resolved and that AdGuard is once again working as intended. Sometimes technology can be unpredictable, and it's reassuring to know that a simple reinstallation can often resolve such problems.

**Comment by Khaled0Ebrahim** [comment]
From the data you already sent I suspect that you used multiple dns servers one's using https and other using tcp and udp
I think there is a problem when you use different types together (it is a bug and it shouldn't really happen).

**Comment by Khaled0Ebrahim** [comment]
I see in the data you already provided that you are using doh which needs a regular dns server to solve the url
in this case it uses the ip addresses in Bootstrap DNS servers
if you modified those or used an ip that doesn't solve the url then it might cause the issue

**Comment by Khaled0Ebrahim** [comment]
@zitev looks like you misunderstood how this works
this place you try to put it in takes only urls for text files that contains multiple urls not the urls itself you trying to allow
to allow the url you can do this in custom filters

**Comment by Khaled0Ebrahim** [comment]
Read the docs and if you need more help feel free to ask

**Comment by LeonLionHeart** [comment]
> [@zitev](https://github.com/zitev) looks like you misunderstood how this works this place you try to put it in takes only urls for text files that contains multiple urls not the urls itself you trying to allow to allow the url you can do this in custom filters

I'm pretty sure it was not a misunderstanding when the devs literally wrote:


<img width="366" alt="Image" src="https://github.com/user-attachments/assets/aaf7509b-6be8-48d1-93b6-c64eab14d890" />
